apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sandbox
  annotations:
    github.com/project-slug: josh-padnick/sandbox
spec:
  type: other
  lifecycle: unknown
  owner: acme-corp
